// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mgo "gopkg.in/mgo.v2"
import mock "github.com/stretchr/testify/mock"

// Database is an autogenerated mock type for the Database type
type Database struct {
	mock.Mock
}

// BulkInsert provides a mock function with given fields: _a0, _a1
func (_m *Database) BulkInsert(_a0 string, _a1 ...interface{}) (*mgo.BulkResult, error) {
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _a1...)
	ret := _m.Called(_ca...)

	var r0 *mgo.BulkResult
	if rf, ok := ret.Get(0).(func(string, ...interface{}) *mgo.BulkResult); ok {
		r0 = rf(_a0, _a1...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mgo.BulkResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, ...interface{}) error); ok {
		r1 = rf(_a0, _a1...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Collection provides a mock function with given fields: _a0
func (_m *Database) Collection(_a0 string) *mgo.Collection {
	ret := _m.Called(_a0)

	var r0 *mgo.Collection
	if rf, ok := ret.Get(0).(func(string) *mgo.Collection); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mgo.Collection)
		}
	}

	return r0
}

// Find provides a mock function with given fields: _a0, _a1
func (_m *Database) Find(_a0 string, _a1 interface{}) *mgo.Query {
	ret := _m.Called(_a0, _a1)

	var r0 *mgo.Query
	if rf, ok := ret.Get(0).(func(string, interface{}) *mgo.Query); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mgo.Query)
		}
	}

	return r0
}

// SetGeoSpatialIndex provides a mock function with given fields: _a0
func (_m *Database) SetGeoSpatialIndex(_a0 string) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
