version: '2'
services:
  state-api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    volumes:
      - ./:/go/src/github.com/emmac1016/state-api
    links:
      - mongo
    ports:
      - "8080:8080"

  mongo:
    image: mongo
    command: --smallfiles