version: '2'
services:
  state-api:
    container_name: state-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    volumes:
      - ./:/go/src/github.com/emmac1016/state-api
    links:
      - mongo
    ports:
      - "8080:8080"

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./docker/data:/data
      - "./build/docker/scripts/:/docker-entrypoint-initdb.d/"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PW}
      - MONGO_ROOT_USER=${MONGO_ROOT_USER}
      - MONGO_ROOT_PW=${MONGO_ROOT_PW}
      - MONGO_DB=${MONGO_DB}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PW=${MONGO_PW}