// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Bulk is an autogenerated mock type for the Bulk type
type Bulk struct {
	mock.Mock
}

// Insert provides a mock function with given fields: docs
func (_m *Bulk) Insert(docs ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, docs...)
	_m.Called(_ca...)
}

// Run provides a mock function with given fields:
func (_m *Bulk) Run() {
	_m.Called()
}

// Unordered provides a mock function with given fields:
func (_m *Bulk) Unordered() {
	_m.Called()
}
