// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mgo "gopkg.in/mgo.v2"
import mock "github.com/stretchr/testify/mock"

// Collection is an autogenerated mock type for the Collection type
type Collection struct {
	mock.Mock
}

// Bulk provides a mock function with given fields:
func (_m *Collection) Bulk() *mgo.Bulk {
	ret := _m.Called()

	var r0 *mgo.Bulk
	if rf, ok := ret.Get(0).(func() *mgo.Bulk); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mgo.Bulk)
		}
	}

	return r0
}

// EnsureIndex provides a mock function with given fields: _a0
func (_m *Collection) EnsureIndex(_a0 mgo.Index) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(mgo.Index) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: _a0
func (_m *Collection) Find(_a0 interface{}) *mgo.Query {
	ret := _m.Called(_a0)

	var r0 *mgo.Query
	if rf, ok := ret.Get(0).(func(interface{}) *mgo.Query); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mgo.Query)
		}
	}

	return r0
}
