// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Database is an autogenerated mock type for the Database type
type Database struct {
	mock.Mock
}

// C provides a mock function with given fields: name
func (_m *Database) C(name string) *Collection {
	ret := _m.Called(name)

	var r0 *Collection
	if rf, ok := ret.Get(0).(func(string) *Collection); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Collection)
		}
	}

	return r0
}
